# Generated by Django 6.0.5 on 2026-05-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('source_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
